// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yb.Api.Data;

#nullable disable

namespace Yb.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Yb.Api.Models.YbUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CheckMemo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CheckStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CheckUserCD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CheckUserNM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateUserCD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreateUserNM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DataAuthority")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentCD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DepartmentNM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifyUserCD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pinyin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RoleID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<string>("UserCD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserNM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("YbUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
